project:
  type: book

book:
  title: "Pengantar Optimisasi dalam Industri"
  author: "Ikang Fadhli"
  date: "8/26/2025"
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - prakata.qmd
    - index.qmd
    - pre_1.qmd
    - pre_2.qmd
    - pre_3.qmd
    - pre_4.qmd
    - pre_5.qmd
    - pre_6.qmd
    - pre_7.qmd
    - pre_8.qmd
    - pre_9.qmd
    - pre_10.qmd

comments:
  hypothesis: true
  
highlight-style: pygments

format:
  html:
    theme: united
    code-copy: true
    cover-image: optim.png
    message: false
    warning: false
