# *SOLVER* UNTUK OPTIMISASI

## Menggunakan **R**

Untuk menyelesaikan masalah optimisasi menggunakan **R**, ada beberapa cara yang bisa digunakan, yakni:

1.  Menggunakan `ompr` *packages*.
2.  Membuat algoritma *dynamic spiral*.

| Algoritma        | Bentuk obj function   | Banyak obj function   |
|------------------|-----------------------|-----------------------|
| `ompr`           | Linear                | *Single obj function* |
| *Dynamic spiral* | Linear dan non linear | *Single obj function* |

## Menggunakan **Python**

Selain **R**, kita juga bisa memanfaatkan *open source* *libraries* buatan:

1.  **Meta** seperti **Nevergrad**[^pre_4-1]. Digunakan untuk menyelesaikan *multi objective optimization*.
2.  **Google** seperti **OR Tools**[^pre_4-2]. Digunakan untuk menyelesaikan *single objective optimization*.
3. __PyMoo__[^pre_4-3] yang digunakan untuk menyelesaikan *multi objective optimization*.

[^pre_4-1]: https://facebookresearch.github.io/nevergrad/

[^pre_4-2]: https://developers.google.com/optimization

[^pre_4-3]: https://pymoo.org/

| Libraries   | Bentuk obj function | Banyak obj function   |
|-------------|---------------------|-----------------------|
| `or tools`  | Linear              | *Single obj function* |
| *Nevergrad* | Linear              | *Multi obj function*  |
| *Pymoo*     | Linear              | *Multi obj function*  |
